events {}

http {

    upstream gotenberg_backend {

        server gotenberg:3000;

    }


    server {

        listen 8080;


        location / {

            proxy_pass http://gotenberg_backend;

        }

    }

}
