apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opslens
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/farhaan4022/opslens.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: opslens

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
